config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
  resources :user_events, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :user_events, foreign_key: :attended_event_id
  has_many :attendees, through: :user_events, foreign_key: :attendee_id
  validates :date_event, presence: true
  default_scope -> { order(date_event: :asc) }
  scope :upcoming, -> { where('date_event >= ?', Time.zone.now) }
  scope :past, -> { where('date_event < ?', Time.zone.now) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :user_events, foreign_key: :attendee_id
  has_many :attended_events, through: :user_events

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def upcoming_events
    upc_events = []
    attended_events.each do |event|
      upc_events.push(event) if event.date_event >= Time.zone.now
    end
    upc_events
  end

  def previous_events
    past_ev = []
    attended_events.each do |event|
      past_ev.push(event) if event.date_event < Time.zone.now
    end
    past_ev
  end
end

app/models/user_event.rb
# frozen_string_literal: true

class UserEvent < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  helper_method :current_user?

  # Returns true if the user is logged in,il false otherwise.
  def logged_in?
    !current_user.nil?
  end

  helper_method :logged_in?

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :logged_in_user, only: %i[new create]
  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(events_params)
    if @event.save
      flash[:success] = 'Event created successfully'
      redirect_to event_path(@event)
    else
      flash.now[:danger] = 'Failed to create a new event'
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @userevent = UserEvent.new
  end

  def index
    @events_upcoming = Event.upcoming
    @events_past = Event.past
  end

  private

  def events_params
    params.require(:event).permit(:name, :location, :date_event, :description)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      sign_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    @events_upcoming = Event.upcoming
    @events_past = Event.past
  end
end

app/controllers/user_events_controller.rb
# frozen_string_literal: true

class UserEventsController < ApplicationController
  before_action :logged_in_user, only: %i[create]
  def create
    event = Event.find(user_event_params[:attended_event])
    @userevent = UserEvent.new(attendee: current_user, attended_event: event)
    if @userevent.save
      flash[:success] = 'You were registered successfully'
    else
      flash.now[:danger] = 'You are already registered!'
    end
    redirect_to event_path(@userevent.attended_event)
  end

  private

  def user_event_params
    params.require(:user_event).permit(:attended_event)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      flash[:success] = 'Welcome to the Private Events!!'
      redirect_to user_path(@user)
    else
      flash.now[:danger] = 'Email already registered'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @prev_events = @user.previous_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/user_events_helper.rb
# frozen_string_literal: true

module UserEventsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<section class="all-events"> 
    <h1>ALL EVENTS</h1>
    <% if logged_in? %>
        <p>User name: <%= current_user.name %></p>
    <% end %>
    <% @events_upcoming.each do |event| %>
    <div>
        <p><%= event.name %></p>
        <p><%= event.location %></p>
        <p><%= event.date_event %></p>
        <p><%= event.description %></p>
    </div>
    <% end %>
    <% @events_past.each do |event| %>
    <div>
        <p><%= event.name %></p>
        <p><%= event.location %></p>
        <p><%= event.date_event %></p>
        <p><%= event.description %></p>
    </div>
    <% end %>

    <div id='create-event'>
        <%= link_to "Create event", new_event_path %>
    </div>
</section> 

app/views/events/new.html.erb
<section class="create-event">
<h1>Create an event</h1>
<%= form_for(@event, url: events_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :location %>
      <%= f.text_field :location %>

      <%= f.label :date_event %>
      <%= f.date_field :date_event %>

      <%= f.label :description %>
      <%= f.text_area :description, cols: 20, rows: 20 %>

      <%= f.submit 'Create Event' %>
<% end %>
</section>

app/views/events/show.html.erb
<section class="single-event">
<h1><%= @event.name %></h1>
<p>Location: <%= @event.location %></p>
<p>Date: <%= @event.date_event %></p>
<p>Description: <%= @event.description %></p>
<p>Attendees: <%= pluralize(@event.attendees.length, 'person') %></p>
<% if logged_in? %>
<ul>
    <% @event.attendees.each do |attendee| %>
    <li>Name: <%= attendee.name %>, email: <%= attendee.email %></li>
    <% end %>
</ul>
<% end %>
<% if @event.date_event > Time.now && !@event.attendees.include?(current_user)  %>
    <%= form_for @userevent do |f| %>

        <%= f.hidden_field :attended_event, :value => @event.id %>

        <%= f.submit "Register" %>
    <% end %>
<% end %>
</section>

app/views/layouts/_header.html.erb
<header>
  <div>
    <%= link_to "Private Events", root_path , id: "logo" %>
  </div>
  <nav>
    <ul>
      <li><%= link_to "All Events", root_path %></li>
        <% if logged_in? %>
          <ul>
            <li>
              <%= link_to "Create Event", new_event_path %>
            </li>
            <li>
              <%= link_to "My Profile", user_path(current_user) %>
            </li>
            <li>
              <%= link_to "Sign out", logout_path, method: :delete %>
            </li>
          </ul>
      <% else %>
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "Sign in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_event.html.erb
<% events.each do |event| %>
<ul class="item-events">
    <li>Event Name: <%= link_to event.name, event_path(event) %></li>
    <li>Location: <%= event.location %></li>
    <li><%= time_tag event.date_event %></li>
</ul>
<% end %>

app/views/static_pages/home.html.erb
<div class="main-image">
<div class="static-page-title">
    <div>Made for</div>
    <div>those who do</div>
</div>
</div>
<section class="all-events"> 
    <h1>ALL EVENTS</h1>
    <p class="title-events">Upcoming Events</p>
    <%= render partial:'shared/event', locals: { events: @events_upcoming } %>
    <p class="title-events">Past Events</p>
    <%= render partial:'shared/event', locals: { events: @events_past } %>
</section> 

app/views/user_events/create.html.erb
<h1>UserEvents#create</h1>
<p>Find me in app/views/user_events/create.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<section class="forms sign-up">
<h1>SIGN UP</h1>
<%#= render 'shared/error_messages' %>
<%= form_for(@user, url: users_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.submit "Create my account" %>
<% end %>
</section>

app/views/users/show.html.erb
<section class="all-events"> 
    <% if logged_in? %>
        <p>Hey!! <%= current_user.name %></p>

        <div id='links-event'>
            <button type="button"><%= link_to "Create event", new_event_path %></button>
            <button type="button"><%= link_to "Check all the events in Private-Events", root_path %></button>
        </div>
    <% end %>
    <p class="title-events">Your Created Events</p>
    <%= render partial:'shared/event', locals: { events: current_user.created_events } %>
    <p class="title-events">Your Upcoming Events</p>
    <%= render partial:'shared/event', locals: { events: @upcoming_events } %>
    <p class="title-events">Your Past Events</p>
    <%= render partial:'shared/event', locals: { events: @prev_events } %>
</section>
</ul>